export default () => [
	{name: 'Afghanistan', statsCode: 'AF', timelineCode: 'AF'},
	{name: 'Albania', statsCode: 'AL', timelineCode: 'AL'},
	{name: 'Algeria', statsCode: 'DZ', timelineCode: 'DZ'},
	{name: 'Angola', statsCode: 'AO', timelineCode: 'AO'},
	{name: 'Argentina', statsCode: 'AR', timelineCode: 'AR'},
	{name: 'Armenia', statsCode: 'AM', timelineCode: 'AM'},
	{name: 'Australia', statsCode: 'AU', timelineCode: 'AU'},
	{name: 'Austria', statsCode: 'AT', timelineCode: 'AT'},
	{name: 'Azerbaijan', statsCode: 'AZ', timelineCode: 'AZ'},
	{name: 'Bahamas', statsCode: 'BS', timelineCode: 'BS'},
	{name: 'Bangladesh', statsCode: 'BD', timelineCode: 'BD'},
	{name: 'Belarus', statsCode: 'BY', timelineCode: 'BY'},
	{name: 'Belgium', statsCode: 'BE', timelineCode: 'BE'},
	{name: 'Belize', statsCode: 'BZ', timelineCode: 'BZ'},
	{name: 'Benin', statsCode: 'BJ', timelineCode: 'BJ'},
	{name: 'Bhutan', statsCode: 'BT', timelineCode: 'BT'},
	{name: 'Bolivia', statsCode: 'BO', timelineCode: 'BO'},
	{name: 'Bosnia and Herzegovina', statsCode: 'BA', timelineCode: 'BA'},
	{name: 'Botswana', statsCode: 'BW', timelineCode: 'BW'},
	{name: 'Brazil', statsCode: 'BR', timelineCode: 'BR'},
	{name: 'Brunei Darussalam', statsCode: 'BN', timelineCode: 'BN'},
	{name: 'Bulgaria', statsCode: 'BG', timelineCode: 'BG'},
	{name: 'Burkina Faso', statsCode: 'BF', timelineCode: 'BF'},
	{name: 'Burundi', statsCode: 'BI', timelineCode: 'BI'},
	{name: 'Cambodia', statsCode: 'KH', timelineCode: 'KH'},
	{name: 'Cameroon', statsCode: 'CM', timelineCode: 'CM'},
	{name: 'Canada', statsCode: 'CA', timelineCode: 'CA'},
	{name: 'Ivory Coast', statsCode: 'CI', timelineCode: 'CI'},
	{name: 'Central African Republic', statsCode: 'CF', timelineCode: 'CF'},
	{name: 'Chad', statsCode: 'TD', timelineCode: 'TD'},
	{name: 'Chile', statsCode: 'CL', timelineCode: 'CL'},
	{name: 'China', statsCode: 'CN', timelineCode: 'CN'},
	{name: 'Colombia', statsCode: 'CO', timelineCode: 'CO'},
	{name: 'Congo', statsCode: 'CG', timelineCode: 'CG'},
	{name: 'Democratic Republic of Congo', statsCode: 'CD', timelineCode: 'CD'},
	{name: 'Costa Rica', statsCode: 'CR', timelineCode: 'CR'},
	{name: 'Croatia', statsCode: 'HR', timelineCode: 'HR'},
	{name: 'Cuba', statsCode: 'CU', timelineCode: 'CU'},
	{name: 'Cyprus', statsCode: 'CY', timelineCode: 'CY'},
	{name: 'Czechia', statsCode: 'CZ', timelineCode: 'CZ'},
	{name: 'Denmark', statsCode: 'DK', timelineCode: 'DK'},
	{name: 'Diamond Princess', statsCode: 'DP', timelineCode: 'DP'},
	{name: 'Djibouti', statsCode: 'DJ', timelineCode: 'DJ'},
	{name: 'Dominican Republic', statsCode: 'DO', timelineCode: 'DO'},
	{name: 'DR Congo', statsCode: 'CD', timelineCode: 'CD'},
	{name: 'Ecuador', statsCode: 'EC', timelineCode: 'EC'},
	{name: 'Egypt', statsCode: 'EG', timelineCode: 'EG'},
	{name: 'El Salvador', statsCode: 'SV', timelineCode: 'SV'},
	{name: 'Equatorial Guinea', statsCode: 'GQ', timelineCode: 'GQ'},
	{name: 'Eritrea', statsCode: 'ER', timelineCode: 'ER'},
	{name: 'Estonia', statsCode: 'EE', timelineCode: 'EE'},
	{name: 'Ethiopia', statsCode: 'ET', timelineCode: 'ET'},
	{name: 'Falkland Islands', statsCode: 'FK', timelineCode: 'FK'},
	{name: 'Fiji', statsCode: 'FJ', timelineCode: 'FJ'},
	{name: 'Finland', statsCode: 'FI', timelineCode: 'FI'},
	{name: 'France', statsCode: 'FR', timelineCode: 'FR'},
	{name: 'French Guiana', statsCode: 'GF', timelineCode: 'GF'},
	{name: 'French Southern Territories', statsCode: 'TF', timelineCode: 'TF'},
	{name: 'Gabon', statsCode: 'GA', timelineCode: 'GA'},
	{name: 'Gambia', statsCode: 'GM', timelineCode: 'GM'},
	{name: 'Georgia', statsCode: 'GE', timelineCode: 'GE'},
	{name: 'Germany', statsCode: 'DE', timelineCode: 'DE'},
	{name: 'Ghana', statsCode: 'GH', timelineCode: 'GH'},
	{name: 'Greece', statsCode: 'GR', timelineCode: 'GR'},
	{name: 'Greenland', statsCode: 'GL', timelineCode: 'GL'},
	{name: 'Guatemala', statsCode: 'GT', timelineCode: 'GT'},
	{name: 'Guinea', statsCode: 'GN', timelineCode: 'GN'},
	{name: 'Guinea-Bissau', statsCode: 'GW', timelineCode: 'GW'},
	{name: 'Guyana', statsCode: 'GY', timelineCode: 'GY'},
	{name: 'Haiti', statsCode: 'HT', timelineCode: 'HT'},
	{name: 'Honduras', statsCode: 'HN', timelineCode: 'HN'},
	{name: 'Hong Kong', statsCode: 'HK', timelineCode: 'HK'},
	{name: 'Hungary', statsCode: 'HU', timelineCode: 'HU'},
	{name: 'Iceland', statsCode: 'IS', timelineCode: 'IS'},
	{name: 'India', statsCode: 'IN', timelineCode: 'IN'},
	{name: 'Indonesia', statsCode: 'ID', timelineCode: 'ID'},
	{name: 'Iran', statsCode: 'IR', timelineCode: 'IR'},
	{name: 'Iraq', statsCode: 'IQ', timelineCode: 'IQ'},
	{name: 'Ireland', statsCode: 'IE', timelineCode: 'IE'},
	{name: 'Israel', statsCode: 'IL', timelineCode: 'IL'},
	{name: 'Italy', statsCode: 'IT', timelineCode: 'IT'},
	{name: 'Jamaica', statsCode: 'JM', timelineCode: 'JM'},
	{name: 'Japan', statsCode: 'JP', timelineCode: 'JP'},
	{name: 'Jordan', statsCode: 'JO', timelineCode: 'JO'},
	{name: 'Kazakhstan', statsCode: 'KZ', timelineCode: 'KZ'},
	{name: 'Kenya', statsCode: 'KE', timelineCode: 'KE'},
	{name: 'Korea', statsCode: 'KP', timelineCode: 'KP'},
	{name: 'Kosovo', statsCode: 'XK', timelineCode: 'XK'},
	{name: 'Kuwait', statsCode: 'KW', timelineCode: 'KW'},
	{name: 'Kyrgyzstan', statsCode: 'KG', timelineCode: 'KG'},
	{name: 'Lao', statsCode: 'LA', timelineCode: 'LA'},
	{name: 'Latvia', statsCode: 'LV', timelineCode: 'LV'},
	{name: 'Lebanon', statsCode: 'LB', timelineCode: 'LB'},
	{name: 'Lesotho', statsCode: 'LS', timelineCode: 'LS'},
	{name: 'Liberia', statsCode: 'LR', timelineCode: 'LR'},
	{name: 'Libya', statsCode: 'LY', timelineCode: 'LY'},
	{name: 'Lithuania', statsCode: 'LT', timelineCode: 'LT'},
	{name: 'Luxembourg', statsCode: 'LU', timelineCode: 'LU'},
	{name: 'Macedonia', statsCode: 'MK', timelineCode: 'MK'},
	{name: 'Madagascar', statsCode: 'MG', timelineCode: 'MG'},
	{name: 'Malawi', statsCode: 'MW', timelineCode: 'MW'},
	{name: 'Malaysia', statsCode: 'MY', timelineCode: 'MY'},
	{name: 'Mali', statsCode: 'ML', timelineCode: 'ML'},
	{name: 'Mauritania', statsCode: 'MR', timelineCode: 'MR'},
	{name: 'Mexico', statsCode: 'MX', timelineCode: 'MX'},
	{name: 'Moldova', statsCode: 'MD', timelineCode: 'MD'},
	{name: 'Mongolia', statsCode: 'MN', timelineCode: 'MN'},
	{name: 'Montenegro', statsCode: 'ME', timelineCode: 'ME'},
	{name: 'Morocco', statsCode: 'MA', timelineCode: 'MA'},
	{name: 'Mozambique', statsCode: 'MZ', timelineCode: 'MZ'},
	{name: 'Myanmar', statsCode: 'MM', timelineCode: 'MM'},
	{name: 'Namibia', statsCode: 'NA', timelineCode: 'NA'},
	{name: 'Nepal', statsCode: 'NP', timelineCode: 'NP'},
	{name: 'Netherlands', statsCode: 'NL', timelineCode: 'NL'},
	{name: 'New Caledonia', statsCode: 'NC', timelineCode: 'NC'},
	{name: 'New Zealand', statsCode: 'NZ', timelineCode: 'NZ'},
	{name: 'Nicaragua', statsCode: 'NI', timelineCode: 'NI'},
	{name: 'Niger', statsCode: 'NE', timelineCode: 'NE'},
	{name: 'Nigeria', statsCode: 'NG', timelineCode: 'NG'},
	{name: 'North Korea', statsCode: 'KP', timelineCode: 'KP'},
	{name: 'Norway', statsCode: 'NO', timelineCode: 'NO'},
	{name: 'Oman', statsCode: 'OM', timelineCode: 'OM'},
	{name: 'Pakistan', statsCode: 'PK', timelineCode: 'PK'},
	{name: 'Palestine', statsCode: 'PS', timelineCode: 'PS'},
	{name: 'Panama', statsCode: 'PA', timelineCode: 'PA'},
	{name: 'Papua New Guinea', statsCode: 'PG', timelineCode: 'PG'},
	{name: 'Paraguay', statsCode: 'PY', timelineCode: 'PY'},
	{name: 'Peru', statsCode: 'PE', timelineCode: 'PE'},
	{name: 'Philippines', statsCode: 'PH', timelineCode: 'PH'},
	{name: 'Poland', statsCode: 'PL', timelineCode: 'PL'},
	{name: 'Portugal', statsCode: 'PT', timelineCode: 'PT'},
	{name: 'Puerto Rico', statsCode: 'PR', timelineCode: 'PR'},
	{name: 'Qatar', statsCode: 'QA', timelineCode: 'QA'},
	{name: 'Republic of Kosovo', statsCode: 'XK', timelineCode: 'XK'},
	{name: 'Romania', statsCode: 'RO', timelineCode: 'RO'},
	{name: 'Russia', statsCode: 'RU', timelineCode: 'RU'},
	{name: 'Rwanda', statsCode: 'RW', timelineCode: 'RW'},
	{name: 'Saudi Arabia', statsCode: 'SA', timelineCode: 'SA'},
	{name: 'Senegal', statsCode: 'SN', timelineCode: 'SN'},
	{name: 'Serbia', statsCode: 'RS', timelineCode: 'RS'},
	{name: 'Sierra Leone', statsCode: 'SL', timelineCode: 'SL'},
	{name: 'Singapore', statsCode: 'SG', timelineCode: 'SG'},
	{name: 'Slovakia', statsCode: 'SK', timelineCode: 'SK'},
	{name: 'Slovenia', statsCode: 'SI', timelineCode: 'SI'},
	{name: 'Solomon Islands', statsCode: 'SB', timelineCode: 'SB'},
	{name: 'Somalia', statsCode: 'SO', timelineCode: 'SO'},
	{name: 'South Africa', statsCode: 'ZA', timelineCode: 'ZA'},
	{name: 'South Korea', statsCode: 'KR', timelineCode: 'KR'},
	{name: 'South Sudan', statsCode: 'SS', timelineCode: 'SS'},
	{name: 'Spain', statsCode: 'ES', timelineCode: 'ES'},
	{name: 'Sri Lanka', statsCode: 'LK', timelineCode: 'LK'},
	{name: 'Sudan', statsCode: 'SD', timelineCode: 'SD'},
	{name: 'Suriname', statsCode: 'SR', timelineCode: 'SR'},
	{name: 'Svalbard and Jan Mayen', statsCode: 'SJ', timelineCode: 'SJ'},
	{name: 'Swaziland', statsCode: 'SZ', timelineCode: 'SZ'},
	{name: 'Sweden', statsCode: 'SE', timelineCode: 'SE'},
	{name: 'Switzerland', statsCode: 'CH', timelineCode: 'CH'},
	{name: 'Syrian Arab Republic', statsCode: 'SY', timelineCode: 'SY'},
	{name: 'Taiwan', statsCode: 'TW', timelineCode: 'TW'},
	{name: 'Tajikistan', statsCode: 'TJ', timelineCode: 'TJ'},
	{name: 'Tanzania', statsCode: 'TZ', timelineCode: 'TZ'},
	{name: 'Thailand', statsCode: 'TH', timelineCode: 'TH'},
	{name: 'Timor-Leste', statsCode: 'TL', timelineCode: 'TL'},
	{name: 'Togo', statsCode: 'TG', timelineCode: 'TG'},
	{name: 'Trinidad and Tobago', statsCode: 'TT', timelineCode: 'TT'},
	{name: 'Tunisia', statsCode: 'TN', timelineCode: 'TN'},
	{name: 'Turkey', statsCode: 'TR', timelineCode: 'TR'},
	{name: 'Turkmenistan', statsCode: 'TM', timelineCode: 'TM'},
	{name: 'UAE', statsCode: 'AE', timelineCode: 'AE'},
	{name: 'Uganda', statsCode: 'UG', timelineCode: 'UG'},
	{name: 'United Kingdom', statsCode: 'GB', timelineCode: 'GB'},
	{name: 'Ukraine', statsCode: 'UA', timelineCode: 'UA'},
	{name: 'USA', statsCode: 'US', timelineCode: 'US'},
	{name: 'Uruguay', statsCode: 'UY', timelineCode: 'UY'},
	{name: 'Uzbekistan', statsCode: 'UZ', timelineCode: 'UZ'},
	{name: 'Vanuatu', statsCode: 'VU', timelineCode: 'VU'},
	{name: 'Venezuela', statsCode: 'VE', timelineCode: 'VE'},
	{name: 'Vietnam', statsCode: 'VN', timelineCode: 'VN'},
	{name: 'Western Sahara', statsCode: 'EH', timelineCode: 'EH'},
	{name: 'Yemen', statsCode: 'YE', timelineCode: 'YE'},
	{name: 'Zambia', statsCode: 'ZM', timelineCode: 'ZM'},
	{name: 'Zimbabwe', statsCode: 'ZW', timelineCode: 'ZW'}
];